security:
  providers:
    our_db_provider:
      entity:
        class: AdministrationBundle:User
        property: username


        #Encoding the User's Password
  encoders:
    #No encoder has been configured for account "Symfony\Component\Security\Core\User\User"
    #we need to add an encoders key:
    AdministrationBundle\Entity\User:
      algorithm: plaintext
  #      cost: 12

  role_hierarchy:
    ROLE_USER:      ROLE_USER
    ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

  firewalls:

    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      form_login:
        login_path: login
        check_path: login
        default_target_path: /
      logout:
        path:   /logout
        target: /




  access_control:
  - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/users, roles: ROLE_SUPERVISOR }
  - { path: ^/admin, roles: ROLE_USER }

