<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIs5reyj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIs5reyj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIs5reyj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIs5reyj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIs5reyj\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Is5reyj',
    'container.build_id' => 'f9f1bbb8',
    'container.build_time' => 1542618807,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIs5reyj');
